version: '3.1'
services:
  web:
    image: php:apache
    container_name: pozos_web
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - pozos_network

  api:
    image: pozos_image:latest
    container_name: pozos_api
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}:/data
    networks:
      - pozos_network
networks:
  pozos_network: